-- DROP TABLE dx20_agent.person;

CREATE TABLE dx20_agent.person (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar NULL
);
INSERT INTO dx20_agent.person (name) VALUES
	 ('Huong'),
	 ('Hieu'),
	 ('Truong'),
	 ('Hieu'),
	 ('MInh'),
	 ('Cuong'),
	 ('Hieu'),
	 ('Huong'),
	 ('Truong'),
	 ('MInh');
INSERT INTO dx20_agent.person (name) VALUES
	 ('Huong'),
	 ('MInh'),
	 ('Hieu'),
	 ('MInh'),
	 ('no_support_ 16'),
	 ('Truong'),
	 ('thread2_ 9319'),
	 ('thread2_ 628');
