-- DROP TABLE dx20_agent.test_entity;

CREATE TABLE dx20_agent.test_entity (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NULL,
	CONSTRAINT test_entity_pkey PRIMARY KEY (id)
);
INSERT INTO dx20_agent.test_entity (name) VALUES
	 ('thread2_ 62'),
	 ('Truong'),
	 ('MInh'),
	 ('Truong'),
	 ('Cuong1'),
	 ('Quang123'),
	 ('Quang123');
